# This file must be included in your mods root directory

# log additional information to the game log.
# recommended to enable while developing, but disable when releasing to Steam Workshop
debugLogging: false

# Generate a template.pot file in mods/strings_templates
generateTranslationsTemplate: true

# Assembly qualified type names to overload strings entries to. Only relevant if you have a C# dll with a STRING-s like class.
stringsOverloadTypes:
  - Beached.STRINGS, Beached

# use {platform} to insert platform keyword, windows|mac|linux 
# looks in moonlet/assets/assetBundles by default. use root:: for root folder of your mod
loadAssetBundles:
  - root::assetbundles/beached_shared_assets

# .bank files are created with FMOD Studio, and can be used to import new sounds
loadFMODBanks:
  - Beached.bank
